image: emediaorg/php:8.1-202303

pipelines:
    default:
        - step:
              caches:
                  - composer
                  - node
              script:
                  - composer update --no-interaction
                  - export PATH="$PATH:$HOME/.composer/vendor/bin"
                  - vendor/bin/phpunit
